# Generated by Django 4.0.1 on 2022-02-10 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("developers", "0002_remove_developer_id_developer_uuid")]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("eb356e1d-95f8-4f33-a110-a53493b35831"), primary_key=True, serialize=False
            ),
        )
    ]
