# Generated by Django 4.0.1 on 2022-03-08 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_alter_developer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('daa20324-fafd-4c0f-be98-cf2050569dee'), primary_key=True, serialize=False),
        ),
    ]
