# Generated by Django 4.0.1 on 2022-04-09 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_alter_developer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='developer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('383842c1-6d50-4e57-90e7-a0ee3946c498'), primary_key=True, serialize=False),
        ),
    ]
